name: Test Library on RN Version

on:
  push:
    branches: [main, dev]
    paths:
      - '.github/workflows/build-react-native-pytorch-core.yml'
      - 'react-native-pytorch-core/android/**'
      - 'react-native-pytorch-core/cxx/**'
      - 'react-native-template-pytorch-live/template/android/**'
      - 'react-native-pytorch-core/package.json'
      - 'react-native-pytorch-core/yarn.lock'
      - 'react-native-template-pytorch-live/template/yarn.lock'
  pull_request:
    paths:
      - '.github/workflows/build-react-native-pytorch-core.yml'
      - 'react-native-pytorch-core/android/**'
      - 'react-native-pytorch-core/cxx/**'
      - 'react-native-template-pytorch-live/template/android/**'
      - 'react-native-pytorch-core/package.json'
      - 'react-native-pytorch-core/yarn.lock'
      - 'react-native-template-pytorch-live/template/yarn.lock'

  workflow_dispatch:

jobs:
  build_with_rn65:
    name: Install Library on RN 0.65 Template
    runs-on: macOS-latest
    defaults:
      run:
        working-directory: .
    steps:
      - uses: actions/checkout@v3
      - name: Setup JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - uses: actions/setup-node@v3
        with:
            node-version: 16
      - name: Publish Library Locally
        run: npx yalc publish
        working-directory: ./react-native-pytorch-core
