name: Test Library on RN Version

on:
  push:
    branches: [main, dev]
    paths:
      - '.github/workflows/build-react-native-pytorch-core.yml'
      - '.github/actions/init-react-native-vanila-template/action.yml'
      - 'react-native-pytorch-core/android/**'
      - 'react-native-pytorch-core/cxx/**'
      - 'react-native-template-pytorch-live/template/android/**'
      - 'react-native-pytorch-core/package.json'
      - 'react-native-pytorch-core/yarn.lock'
      - 'react-native-template-pytorch-live/template/yarn.lock'
  pull_request:
    paths:
      - '.github/workflows/build-react-native-pytorch-core.yml'
      - '.github/actions/init-react-native-vanila-template/action.yml'
      - 'react-native-pytorch-core/android/**'
      - 'react-native-pytorch-core/cxx/**'
      - 'react-native-template-pytorch-live/template/android/**'
      - 'react-native-pytorch-core/package.json'
      - 'react-native-pytorch-core/yarn.lock'
      - 'react-native-template-pytorch-live/template/yarn.lock'

  workflow_dispatch:

jobs:
  build_with_rn65:
    name: Install Library on RN 0.65 Template
    runs-on: macOS-latest
    defaults:
      run:
        working-directory: .
    steps:
      - uses: actions/checkout@v3
      - name: Setup JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - uses: actions/setup-node@v3
        with:
            node-version: 16
      - name: download vanilla template
        run: npx react-native init myrn65 --version 0.65
      - name: install react-native-pytorch-core
        run: yarn add file:./../react-native-pytorch-core
        working-directory: ./myrn65
      - name: add pickFirst
        env:
          nl: '\n'
          prior: '/android {'
          append: "packagingOptions {pickFirst '**/*.so'}"
        run: nl=$'\n' && sed -i '' "${prior}/a\\${nl}${append}${nl}" build.gradle
        working-directory: ./myrn65/android/app
      - name: enlarge jvm capacity
        run: nl=$'\n' && sed -i '' "/FLIPPER_VERSION/a\\${nl}org.gradle.jvmargs=-Xmx8192m${nl}" gradle.properties
        working-directory: ./myrn65/android
      - name: import java package
        run: nl=$'\n' && prior=$'import android.app.Application;' && append=$'import com.facebook.react.bridge.JSIModulePackage; import org.pytorch.rn.core.jsi.PyTorchCoreJSIModulePackage;'  && sed -i '' "/${prior}/a\\${nl}${append}${nl}" MainApplication.java
        working-directory: ./myrn65/android/app/src/main/java/com/myrn65
      - name: overide getJSIModulePackage
        run: nl=$'\n' && prior=$'new ReactNativeHost(this)' && append=$'@Override protected JSIModulePackage getJSIModulePackage(){return new PyTorchCoreJSIModulePackage(); }'  && sed -i '' "/${prior}/a\\${nl}${append}${nl}" MainApplication.java
        working-directory: ./myrn65/android/app/src/main/java/com/myrn65
      - name: build android
        run: ./gradlew assembleDebug
        working-directory: ./myrn65/android
  build_with_rn68:
    name: Install Library on RN 0.68 Template
    runs-on: macOS-latest
    defaults:
      run:
        working-directory: .
    steps:
      - uses: actions/checkout@v3
      - name: Setup JDK 1.11
        uses: actions/setup-java@v1
        with:
          java-version: 1.11
      - uses: actions/setup-node@v3
        with:
            node-version: 16
      - name: download vanilla template
        run: npx react-native init myrn68 --version 0.68
      - name: install react-native-pytorch-core
        run: yarn add file:./../react-native-pytorch-core
        working-directory: ./myrn68
      - name: add pickFirst
        run: nl=$'\n' && sed -i '' "/android {/a\\${nl}packagingOptions {pickFirst '**/*.so'}${nl}" build.gradle
        working-directory: ./myrn68/android/app
      - name: import java package
        run: nl=$'\n' && prior=$'import android.app.Application;' && append=$'import com.facebook.react.bridge.JSIModulePackage; import org.pytorch.rn.core.jsi.PyTorchCoreJSIModulePackage;'  && sed -i '' "/${prior}/a\\${nl}${append}${nl}" MainApplication.java
        working-directory: ./myrn68/android/app/src/main/java/com/myrn68
      - name: overide getJSIModulePackage
        run: nl=$'\n' && prior=$'new ReactNativeHost(this)' && append=$'@Override protected JSIModulePackage getJSIModulePackage(){return new PyTorchCoreJSIModulePackage(); }'  && sed -i '' "/${prior}/a\\${nl}${append}${nl}" MainApplication.java
        working-directory: ./myrn68/android/app/src/main/java/com/myrn68
      - name: build android
        run: ./gradlew assembleDebug
        working-directory: ./myrn68/android
  build_with_rn69:
    name: Install Library on RN 0.69 Template
    runs-on: macOS-latest
    defaults:
      run:
        working-directory: .
    steps:
      - uses: actions/checkout@v3
      - name: Setup JDK 1.11
        uses: actions/setup-java@v1
        with:
          java-version: 1.11
      - uses: actions/setup-node@v3
        with:
            node-version: 16
      - name: download vanilla template
        run: npx react-native init myrn69 --version 0.69
      - name: install react-native-pytorch-core
        run: yarn add file:./../react-native-pytorch-core
        working-directory: ./myrn69
      - name: add pickFirst
        run: nl=$'\n' && sed -i '' "/android {/a\\${nl}packagingOptions {pickFirst '**/*.so'}${nl}" build.gradle
        working-directory: ./myrn69/android/app
      - name: import java package
        run: nl=$'\n' && prior=$'import android.app.Application;' && append=$'import com.facebook.react.bridge.JSIModulePackage; import org.pytorch.rn.core.jsi.PyTorchCoreJSIModulePackage;'  && sed -i '' "/${prior}/a\\${nl}${append}${nl}" MainApplication.java
        working-directory: ./myrn69/android/app/src/main/java/com/myrn69
      - name: overide getJSIModulePackage
        run: nl=$'\n' && prior=$'new ReactNativeHost(this)' && append=$'@Override protected JSIModulePackage getJSIModulePackage(){return new PyTorchCoreJSIModulePackage(); }'  && sed -i '' "/${prior}/a\\${nl}${append}${nl}" MainApplication.java
        working-directory: ./myrn69/android/app/src/main/java/com/myrn69
      - name: build android
        run: ./gradlew assembleDebug
        working-directory: ./myrn69/android
  build_with_rn66:
    name: Install Library on RN 0.66 Template
    runs-on: macOS-latest
    env:
      proj: 'myrn66'
    defaults:
      run:
        working-directory: .
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/init-react-native-vanila-template
        with:
          react-native-version: '0.66'
          project-folder-name: $proj
      - name: install react-native-pytorch-core
        run: yarn add file:./../react-native-pytorch-core
        working-directory: ./$proj
      - name: add pickFirst
        run: nl=$'\n' && sed -i '' "/android {/a\\${nl}packagingOptions {pickFirst '**/*.so'}${nl}" build.gradle
        working-directory: ./$proj/android/app
      - name: enlarge jvm capacity
        run: nl=$'\n' && sed -i '' "/FLIPPER_VERSION/a\\${nl}org.gradle.jvmargs=-Xmx8192m${nl}" gradle.properties
        working-directory: ./$proj/android
      - name: import java package
        run: nl=$'\n' && prior=$'import android.app.Application;' && append=$'import com.facebook.react.bridge.JSIModulePackage; import org.pytorch.rn.core.jsi.PyTorchCoreJSIModulePackage;'  && sed -i '' "/${prior}/a\\${nl}${append}${nl}" MainApplication.java
        working-directory: ./$proj/android/app/src/main/java/com/$proj
      - name: overide getJSIModulePackage
        run: nl=$'\n' && prior=$'new ReactNativeHost(this)' && append=$'@Override protected JSIModulePackage getJSIModulePackage(){return new PyTorchCoreJSIModulePackage(); }'  && sed -i '' "/${prior}/a\\${nl}${append}${nl}" MainApplication.java
        working-directory: ./$proj/android/app/src/main/java/com/$proj
      - name: build android
        run: ./gradlew assembleDebug
        working-directory: ./$proj/android
